- README.md
1. `del` was intentionally omitted. It's not in js-ipfs-api, so let's not commit to it until there's a clear need / demand.
2. js-ipfs-api and js-ipfs core disagree on the return object of `block.stat`. The former is *way* more descriptive than the latter, so we can go with that.
> draft api docs for blocks

- README.md
- src/files.js
This is the beginning of the cat spec. Some notable issues I can think of:
1) The test's aren't currently set up in npm package so I haven't tested the cat test file, but it is just a clone of the js-ipfs core test.
2) Not sure about the promises return. I have to understand promises a bit better or where they are currently being used. js-ipfs-api ```cat``` isn't set up with promises and the js-ipfs cli isn't either to my knowledge. cc @dignifiedquire
> Interface for `ipfs.files.cat` (and alias `ipfs.cat`)

- circle.yml
Instead of running npm test that should fail, lets just print that we have no tests and then exit cleanly
Fixes failing build from here: https://github.com/ipfs/interface-ipfs-core/pull/36
> Run lint instead of test in CircleCI

- package.json
- src/object.js
> feat: update to awesome dag-pb

- API/files/README.md
Documenting JS importer options passed in add stream constructor.
Depends on https://github.com/ipfs/js-ipfs/pull/707
> docs: documenting importer options

- src/pubsub.js
no reason not to have these assertions as part of the suite, tested in js-ipfs, they run fine
> test: last assertions are fine in js-ipfs

- src/pubsub.js
This PR will enable previously the skipped tests for pubsub.peers().
> Enable peer listing tests

- src/files.js
Previously, the test was passing because the end event was being emitted prematurely.
> fix: ending the test only when we are sure we got the root dir out

- src/pubsub.js
Because we used the same topic in all tests, they were suspect of race conditions and one failing introduced failures in other tests. The switch in test runners made those dependencies visible and so tests started failing. With this change those tests are now passing fine as expected.
> fix(pubsub): dynamic topics to avoid race conditions

- src/swarm.js
The reason for this is that js-ipfs expects these to be multiaddrs, when
my expectation was that these could be null and therefore disable the
functionality
> Listen on API and Gateway

- src/pin.js
@diasdavid I ran into a few issues with the tests when trying to get the [pin core interface](https://github.com/ipfs/js-ipfs/pull/107) updated to this spec:
- The default timeout is too short
- The `add` test is checking for a hash string result where the API indicates it should be an object with a hash property
- The recursive `ls` test is run after the recursive pin has been removed, but expects pinset not to be empty.
- The indirect `ls` test is also run after the recursive pin has been removed, but in any case the recursively pinned object has no links, so the indirect pinset is always empty. 
For now I just made small adjustments to get them passing, but I think the pinned object should have at least one link, if not a more complex tree, for a nontrivial test of indirect pins. I …
> Get tests passing with pin core changes

- SPEC/DAG.md
JavaScript implementation would only log the tree for 'a' which would log []
Pretty sure this is an example bug
> fixes example should get the whole tree

- src/files.js
For now, the inly supported `.ls` interface is the promise / callback one:
```js
ipfs.ls(hash, (err, files) => {
// ...
})
```
(According to the [future spec in plan](https://github.com/ipfs/interface-ipfs-core/pull/162), the stream ones do not return a promise, but a direct stream. — saved for later once spec is merged)
> fixed .ls spec

- src/pubsub.js
Rename to topicCIDs should be topicIDs.  See the [background discussion](https://github.com/ipfs/js-ipfs/issues/1068).
> Pubsub message fields

- .travis.yml
- SPEC/FILES.md
- circle.yml
- package.json
- src/files.js
> New Streaming and Buffered Interfaces

- src/pubsub.js
Prevent dialer timeouts and speed up the tests.
This gets all the pubsub tests working!
> aegir test -t node --timeout 5000 -f test\interface\pubsub.spec.js
```
Test Node.js
.pubsub
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
single node
.publish
√ errors on string messags
√ message from buffer
.subscribe
√ to one topic
√ attaches multiple event listeners
√ discover options
multiple nodes connected
.peers
√ does not error when not subscribed to a topic
√ doesn't return extra peers
√ returns peers for a topic - one peer (529ms)
√ lists peers for a topic - multiple peers (526ms)
.ls
√ empty() list when no topics are subscribed
√ list with 1 subscribed topic
√ list with 3 subscribed topics …
```
> fix: swarm connect to local servers

- README.md
Because the link of javascript usage was wrong, it is correct to be changed to #javascript.
> doc: modify javascripte usage link in README.md

- src/files.js
Added 2 specs for `file.cat`:
- when the path is unknown
- when the path is a dir
> specifies files.cat unknown file and dir errors

- src/files.js
> fix: cat not found message in go-ipfs

- src/files.js
As per the discussion in #193 this PR changes the tests involving the progress option to only test that the handler was called, not the number of times the handler was called.
> Ensure progress handler was called, not the specific number of times

- src/miscellaneous.js
Test was previously passing because mocha didn't know it was async and no assertions were made
> Fixes dns test with callback

- SPEC/BITSWAP.md
- SPEC/REPO.md
- SPEC/STATS.md
`stats.repo` is the same as `repo.stat` and the same happens for `stats.bitswap` and `bitswap.stat`. The goal is to remove the repeated documentation.
@diasdavid take a look 😄
> Link stats.repo and stats.bitswap

- js/src/stats.js
Ref.: https://github.com/ipfs/js-ipfs/pull/1198
> Allow stats.bitswap and stats.repo tests to work on JS-IPFS

- SPEC/BLOCK.md
- SPEC/CONFIG.md
- SPEC/DAG.md
- SPEC/DHT.md
- SPEC/FILES.md
- SPEC/MISCELLANEOUS.md
- SPEC/OBJECT.md
- SPEC/PIN.md
- SPEC/PUBSUB.md
- SPEC/SWARM.md
All links to examples are broken, this PR updates them to point to the right places.
> docs: Fix paths to examples

- js/src/dag.js
The current go-ipfs doesn't yet support running all those tests,
but at least part of them. Fix the tests that work and skip the
ones that are not yet supported.
> fix: adapt dag tests to current environment

- SPEC/SWARM.md
- js/src/swarm.js
As per discussion in https://github.com/ipfs/js-ipfs/issues/1248
> fix: docs and adds test assertion that peer is a PeerId in return value from swarm.peers

- js/src/pubsub.js
Always unsubscribe from feeds at the end of the test, even
if there was a failure. This prevents subsequent tests to fail.
Tested with js-ipfs (Linux) and js-ipfs-api (Linux, Windows).
> test: more pubsub test isolation improvements

- js/src/pubsub.js
Skip some tests because pubsub, `go floodsub`, does not make any guarantee on message delivery.
First reported in https://github.com/ipfs/js-ipfs-api/pull/648
```
1) .pubsub multiple nodes connected multiple nodes receive multiple messages:
Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
2) .pubsub multiple nodes connected load tests send/receive 10k messages:
Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
> pubsub makes no guarantee on Windows and with go-ipfs

- SPEC/FILES.md
- js/src/files-mfs.js
- js/src/files.js
Following https://github.com/ipfs/go-ipfs/pull/4638, this new option is present in go-ipfs that enable to know if and how much of a dag is present locally.
Now, in the go-ipfs's http API, `WithLocality`, `Local` and `SizeLocal` in the answer are not present when `with-local` is not active. I chose to set default values in the javascript object response, but it could also be done the same way with no values present at all. Which would be best ?
> complete files.stat with the 'with-local' option

- js/src/files.js
- js/src/stats.js
One test broke due to c4934ca0b3b43f5bfc1ff5dd38f85d945d3244de [1].
If promises are used, you needn't pass `done` as parameter of
the callback in.
[1]: https://github.com/ipfs/interface-ipfs-core/commit/c4934ca0b3b43f5bfc1ff5dd38f85d945d3244de#diff-0a6449ecfa8b9e3d807f53dde24eca71R66
> fix: fix broken stats test

- SPEC/FILES.md
I am updating with a example that does what the comment says `write the file's path and contents to standard out`. It takes the getting started docs and outputs them to the console.
https://ipfs.io/docs/getting-started/
https://jsbin.com/niwadeceze/1/edit?js,output
Closing https://github.com/ipfs/interface-ipfs-core/issues/226
> Update with example outputting the content to stdout

- js/src/dht.js
Without increasing the timeout this test fails on Jenkins way
too often.
> tests: Increase .dht .query timeout

- js/src/dht.js
This should make the tests not fail anymore. The number of nodes was increased so they should pass more often. Before the timeout is reached, the test is skipped. This means that it won't fail even if go-ipfs takes a long time/hangs.
> Harden DHT tests

- SPEC/DHT.md
- js/src/dht.js
As far as I can tell from the [tests](https://github.com/ipfs/interface-ipfs-core/blob/f5f73070c37f374e0516185b8241622d514d09ae/js/src/dht.js#L124) and [`js-ipfs`](https://github.com/ipfs/js-ipfs/blob/e4d2a15143431a9af37a275a149621738c91aa00/src/core/components/dht.js#L119) (follows through to [`js-ipfs-repo`](https://github.com/ipfs/js-ipfs-repo/blob/c30a7f170a631cc6298c06340bd92321b6fe1cd7/src/blockstore.js#L136) `.has` which expects a CID) it just takes a CID. `js-ipfs` implementation also suggests it can [take an array](https://github.com/ipfs/js-ipfs/blob/e4d2a15143431a9af37a275a149621738c91aa00/src/core/components/dht.js#L109).
> Adds missing docs for dht.provide

- js/src/stats.js
Ref.: https://github.com/ipfs/js-ipfs/pull/1230
> Let bandwidth stats tests run on JS-IPFS

- SPEC/FILES.md
- js/src/files.js
This has no dependencies
* Adds the spec to cat files with cid instances
* Adds the failing test for implementation
I'll be submitting PRs to add this functionality to the ipfs/js-ipfs and ipfs/js-ipfs-api repos.
connects ipfs/js-ipfs#1229
> Spec and Test update to support ipfs/js-ipfs#1229

- SPEC/FILES.md
The tests in js-ipfs-api explicitly assert that passing a file path string to `ipfs.add` should fail. 
https://github.com/ipfs/interface-ipfs-core/blob/b862a12bc655954143b995887983f96201abcf31/js/src/files.js#L144-L151
This PR removes "a Path" from the list of possible parameter types to `ipfs.add`
Fixes https://github.com/ipfs/js-ipfs-api/issues/722
> doc: You can't ipfs.add a path

- SPEC/FILES.md
- js/src/files.js
For https://github.com/ipfs/js-ipfs/issues/1178
Adds docs and test for new `wrapWithDirectory` parameter for files.add, files.addStream etc.
Will rely on two other PRs which will also be linked to in that issue.
> feat: add wrapWithDirectory to files.add et al

- SPEC/FILES.md
- js/src/files.js
Requires ipfs/js-ipfs-unixfs-engine#207 and ipfs/js-ipfs#1231 to be merged first.
> doc: Documents the offset/length arguments to ipfs.files.cat and friends

- SPEC/DHT.md
Fix erroneous camel-casing of `findprovs` and `findpeer` in examples.
> Fix dht spec examples

- SPEC/PUBSUB.md
- js/src/pubsub.js
> fix: make pubsub.unsubscribe async and alter pubsub.subscribe signature

- SPEC/BITSWAP.md
- SPEC/BLOCK.md
- SPEC/BOOTSTRAP.md
- SPEC/CONFIG.md
- SPEC/DAG.md
- SPEC/DHT.md
- SPEC/FILES.md
- SPEC/KEY.md
- SPEC/MISCELLANEOUS.md
- SPEC/NAME.md
- SPEC/OBJECT.md
- SPEC/PIN.md
- SPEC/PUBSUB.md
- SPEC/REPO.md
- SPEC/STATS.md
- SPEC/SWARM.md
- SPEC/TYPES.md
- SPEC/UTIL.md
For overview of commands and quick navigation to point on the page the docs are at.
Also tidies up main headings and ensures all commands are prefixed with the subsystem they're in (if any).
> docs: add TOC to specs

- js/src/files-mfs.js
- js/src/files.js
@achingbrain moved the files.stat test to the mfs test suite and added a skip vs console.logging and skipping.
> test: move files.stat to mfs test suite

- js/src/pubsub.js
It is cleared before success callback but not on error.
Previously if this failed it would call the callback again and again every 500ms unleashing chaos on the rest of the tests.
> fix(pubsub): clear interval on error

- js/src/ping.js
- js/src/utils/connections.js
This PR simply changes the ping tests to wait for the two nodes to be connected before starting.
We poll `swarm.peers` every second to check for connectivity and times out after 30s. It means we can distinguish between actual test failures and connectivity problems in the tests.
> fix(ping): wait until nodes are connected before starting ping tests

- SPEC/FILES.md
Further to the conversation on #262 I've swept the mfs api and made what I hope are improvements to consistency and added flags and options where I've found them undocumented in the codebase or where they were otherwise missing.
Most of this has been implemented in [ipfs/js-ipfs-mfs](https://github.com/ipfs/js-ipfs-mfs).
> docs: remove array arguments and document missing options

- SPEC/PIN.md
Current and expected behavior of pin.add, pin.rm is to be recursive by default.
> docs: pin.add, pin.rm are recursive by default

- js/src/bitswap.js
When run in the browser with js-ipfs-api against a stopped go-ipfs there is no error code, just a "Failed to fetch" message from the browser fetch API. The error `code` is specific to Node.js so this check has been removed.
> fix: removes error code checks for bitswap offline tests

- SPEC/FILES.md
This is in line with how the TOC is written on https://github.com/ipfs/js-ipfs-api/blob/master/README.md and makes it much clearer which APIs are for MFS.
> Separate MFS from other files APIs.

- js/src/block.js
Add an empty block and ensure we can get it back successfully. Test for https://github.com/ipfs/js-ipfs-api/pull/789
> test: add test for retrieving an empty block

- js/src/dag/put.js
These tests test code that looks for relevant fields in the passed arguments to turn into DAGNodes in both the Go and JS implementations, which looks like the right thing to do.
> test: remove tests that test duck typing

- js/src/utils/mocha.js
- js/src/utils/suite.js
This PR simply fixes `getDescribe` to also allow you to skip an entire suite using the object syntax (`{ name: 'test name', reason: 'why it was skipped' }`) but with only a name and not a reason. It also tightens up the check for object so that things also considered 'object' according to `typeof` don't also get through ahem `null`, `undefined`, `[]` etc.
> fix: allow skip with object but no reason

- js/src/utils/mocha.js
If a suite of tests has a `skip` array, when adding a `only: true`, the skipped tests start to run again, which makes it hard to isolate a suite. This change allows skipped tests to be skipped and not have the `only` applied. This results in the tests not showing up in the output.
Example
```js
tests.key(defaultCommonFactory, {
only: true,
skip: [
// key.export
{
name: 'export',
reason: 'TODO not implemented in go-ipfs yet'
},
// key.import
{
name: 'import',
reason: 'TODO not implemented in go-ipfs yet'
}
]
})
```
**Before**
```
interface-ipfs-core tests
.key.gen
✓ should generate a new rsa key (106ms)
.key.list
✓ should list all the keys (246ms)
.key.rename
✓ should rename a key (156ms)
.key.rm
✓ should rm a key (178ms)
.key.export
1) should export "self" key
.key.import
2) should import …
```
> Allow passing only to suites with skip lists

- js/src/bitswap/unwant.js
- js/src/bitswap/wantlist.js
- js/src/dht/findpeer.js
- js/src/dht/findprovs.js
- js/src/dht/get.js
- js/src/dht/provide.js
- js/src/dht/query.js
- js/src/key/list.js
- js/src/ping/ping-pull-stream.js
- js/src/ping/ping-readable-stream.js
- js/src/ping/ping.js
- js/src/pubsub/ls.js
- js/src/pubsub/peers.js
- js/src/pubsub/publish.js
- js/src/pubsub/subscribe.js
- js/src/pubsub/unsubscribe.js
- js/src/pubsub/utils.js
- js/src/utils/swarm.js
During the refactor (https://github.com/ipfs/interface-ipfs-core/pull/290) I took the opportunity to parallelise some pubsub operations that didn't explicitly depend on each other. This worked perfectly while testing locally, but on CI it is a different story. I found that tests for js-ipfs-api (which are run against go-ipfs) failed for seemingly random reasons.
After much investigation I finally tried re-serialising the operations I had refactored to be parallel and the tests started to pass. It seems that the pubsub implementation in go-ipfs has some issues with concurrency.
I also found two intermittent issues with `swarm.connect` in go-ipfs (seen significantly more often on CI):
1. Issuing two calls to this function from the same node might end up in the second not actually creating a …
> fix: revert to serialized pubsub operations

- js/src/dag/put.js
As discussed in https://github.com/ipfs/js-ipfs/pull/1419#issuecomment-402441180
at the time of this commit, `dag.put()` basically ignores the `hashAlg`
option, as it passes it down to `ipld.put()`, which won't honor it until
https://github.com/ipld/js-ipld/pull/133 is merged.
Once https://github.com/ipld/js-ipld/pull/133 is merged, this test verifies
that e.g.
```
dag.put(cborNode, {
format: 'dag-cbor',
hashAlg: 'sha3-512'
}, (err, cid) => {
...
})
```
Actually results in a `CID` instance that decodes to `sha3-512` and not
the `sha2-256` default.
License: MIT
Signed-off-by: Pascal Precht pascal.precht@gmail.com
> test(dag): add test to verify put API overrides hash algorithm

- SPEC/DAG.md
Signifies params that are actually optional and does it in a way that is consistent with other spec docs.
> docs(dag): signify optional params and do it consistently

- .aegir.js
- js/src/bitswap/unwant.js
- js/src/bitswap/wantlist.js
- js/src/key/list.js
- js/src/key/rename.js
- js/src/key/rm.js
- js/src/pubsub/subscribe.js
- js/src/utils/swarm.js
- package.json
When the JS code was moved into the js/ directory the aegir linting task was no longer considering them for linting. This is because the default globs do not include this path.
This PR adds custom lint globs to the aegir config and fixes linting errors.
depends on ipfs/aegir#240
License: MIT
Signed-off-by: Alan Shaw <alan@tableflip.io>
> chore: re-enable linting

- js/src/files/stat.js
Not sure why this is still skipped.
> test: enable test stat with ipfs paths

- SPEC/BLOCK.md
- SPEC/CONFIG.md
- SPEC/DAG.md
- SPEC/DHT.md
- SPEC/FILES.md
- SPEC/MISCELLANEOUS.md
- SPEC/OBJECT.md
- SPEC/PIN.md
- SPEC/PUBSUB.md
- SPEC/SWARM.md
Links to examples were broken in various SPEC files due to recent code refactor. So I've updated them.
> revised example links in various SPEC files

- SPEC/FILES.md
Documents the new options added by ipfs/js-ipfs#1454 as well as the missing `long` option from `files.ls`.
> docs: add cid-base and missing ls options for mfs operations

- js/src/files/ls.js
Previously we'd get files in different orders between `files.ls()` and `files.ls({long: true})` due to a bug in `go-ipfs` (see ipfs/go-ipfs#5181)
Since this has been resolved we can now expect consistent ordering.
> test: make files.ls results ordering consistent

- js/src/miscellaneous/resolve.js
Looks like this passes most of the time but sometimes takes longer than the default 5s https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/feat%2Fresolve-cmd-rebase/1/pipeline/17
> fix: give more time for teardown after resolve

- js/src/files/read-readable-stream.js
- js/src/files/read.js
Js says 'file did not exist', go says 'file does not exist'.
> fix: update error messages in line with go

- js/src/miscellaneous/dns.js
Until we have a good way to mock out a DNS server in node and the browser this will hopefully decrease test failures when the external network or `https://ipfs.io/api/v0/dns` is slow or busy.
> fix: allow retries for DNS test due to dependence on external services

- js/src/object/get.js
- package.json
This follows on from ipfs/js-ipfs#1398 and tests the more general case.
Seems to fail with the current master of js-ipfs-api.
> test: adds test vulnerable to encoding translation

- SPEC/MISCELLANEOUS.md
- fix broken link for version example
- make all links more specific
> fix: example links in miscellaneous spec section

- SPEC/FILES.md
Some return values of the callbacks weren't correctly indented, which
made things unpleasant to read.
> docs: format callback return values correctly

- js/src/files/stat.js
If `x` has a property explicitly set to `undefined` then `expect(y).to.eql(x)` requires `y` to also have a property set to undefined. This PR relaxes that requirement to also allow `y` to simply not have the property.
This is to save having to explicitly re-define this property to undefined when `y` has been `JSON.stringify`'d. This happens in the ipfs-postmsg-proxy and this change removes the need for the proxy to know the shape of this object (or at least which properties might have been undefined).
> refactor: relax check for undefined property

- js/src/block/put.js
Previously this test was using the default options so we weren't able to tell if the output was correct when given options that weren't the defaults!
> fix: test for buffer with options

- js/src/types.js
Prior to this change the `ipld-dag-cbor` and `ipld-dag-pb` modules
are re-exported so that can be accessed within the Browser bundle.
Those modules normally don't need to be used directly, they are
kind of implementation details of IPLD. Hence remove them.
> chore: remove ipld formats re-export

- SPEC/FILES.md
I've spent an hour trying to figure out how to do `ipfs add` in the browser: docs describe the "Buffer" part really vaguely and don't mention that `ipfs.files.add` in fact creates a directory object unless used with a correctly created buffer. It works with an incorrectly created buffer, but creates a directory with auto-generated name:
```js
let data = new Uint8Array([0x41, 0x42, 0x43]);
let results = await ipfs.files.add(data);
```
Here `results` is
```json
[
{
"path": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
"hash": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
"size": 4
}
]
```
Now open this hash in `ipfs.io` and try to figure out wtf that is and why size is 4. The `ipfs.types.Buffer` was the key.
> ipfs.files.add: Notes about ipfs.types.Buffer.

- js/src/dht/findpeer.js
- js/src/dht/findprovs.js
Fixes for getting [Awesome Endeavour: DHT Part II](https://github.com/ipfs/js-ipfs/pull/856) on track.
- `findprovs`
The `findproviders` kad-dht function, which is provided by `js-libp2p` through `findprovs` function, receives a `PeerInfo` array in the resulting callback, as [js-libp2p-kad-dht/index.js#L432](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L432). Accordingly, we need to add `p.id`.
- `findpeer`
The `findPeer` kad-dht function, which is provided by `js-libp2p` through kad-dht `findpeer` function, receives an error, if the peer was not found, as [js-libp2p-kad-dht/index.js#L527](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L527). This way, it should receive an error.
> fix: dht find peer and providers

- js/src/ping/ping-pull-stream.js
- js/src/ping/ping-readable-stream.js
- js/src/ping/ping.js
- package.json
These tests take ages locally and are even slower on the Jenkins Mac workers so this PR increases their timeouts to values verging on unreasonable.
> chore: increase ping test timeouts

- js/src/name-pubsub/cancel.js
- js/src/name-pubsub/subs.js
If we have an IPNS record value in cache, we will not hit the resolver and consequently, we are not going to subscribe the topic, as it is only subscribed when we are looking for it.
According to the above, I removed the `publish` prior to the `resolve` in the tests, which lead to some changes in the structure of the test, as resolve will return an error, as a consequence of not having any record.
> fix: ipns over pubsub tests

- SPEC/FILES.md
- js/src/files-mfs/index.js
- js/src/files-mfs/ls-pull-stream.js
- js/src/files-mfs/ls-readable-stream.js
The only `mfs.ls` method at the moment buffers the output into an array before returning it to the user. This PR adds two new methods, `lsPullStream` and `lsReadableStream` to allow the user to either buffer the output themselves (in case they need sorting, etc) or just stream it on to an output of some sort.
> docs: add mfs stream ls methods

- js/src/utils/mocha.js
- js/src/utils/spawn.js
- js/src/utils/swarm.js
- package.json
NOTE: the PRs for https://github.com/ipfs/js-ipfs/issues/1670 are being merged into the `feat/async-iterators` branch. Once they're all in we can merge them into master.
I plan to submit a PR for each subsystem to keep them quick and easy to review.
---
This PR simply converts the modules in `js/src/utils` to use async/await.
Also:
* Removes `async` - we're not going to need this anymore!
* Adds `chai-as-promised` for easier assertions with promises
> refactor: convert utils to use async/await

- SPEC/DHT.md
- js/src/dht/findpeer.js
- js/src/dht/findprovs.js
In the context of the [ipfs/js-ipfs#856](https://github.com/ipfs/js-ipfs/pull/856) and [ipfs/js-ipfs-api/pull/890](https://github.com/ipfs/js-ipfs-api/pull/890)
> fix: update dht responses

- js/src/dht/findpeer.js
Changed to a more correct test for `dht.findPeer`.
`/ipfs/` is removed before the comparison, as we may receive data with or without it.
> fix: dht find peer

- js/src/utils/mocha.js
The only option will now accept an object for onlying a specific test.
Previously you could only do this to only run a specific test:
```js
{
only: ['should test a thing']
}
```
Now you can do this:
```js
{
only: [{
name: 'should test a thing',
reason: 'because development' // optional!
}]
}
```
License: MIT
Signed-off-by: Alan Shaw <alan.shaw@protocol.ai>
> fix: allow only by object

- SPEC/OBJECT.md
- we hit this while refactoring web ui to use the latest ipfs-http-client.
- also fixes incorrectly terminated code fence for rmLink.
> docs: object.patch.addLink param must have cid prop

- src/miscellaneous/resolve.js
1. This is an IPLD path.
2. Resolve really should be resolving up to the last path, not just "failing".
*Neither* js-ipfs *nor* go-ipfs pass this test. However, IMO, a PR is the easiest way to highlight this issue. Thoughts? Objections?
> test: fix resolve test

- README.md
- SPEC/BITSWAP.md
- SPEC/BLOCK.md
- SPEC/BOOTSTRAP.md
- SPEC/CONFIG.md
- SPEC/DAG.md
- SPEC/DHT.md
- SPEC/FILES.md
- SPEC/KEY.md
- SPEC/MISCELLANEOUS.md
- SPEC/NAME.md
- SPEC/OBJECT.md
- SPEC/PIN.md
- SPEC/PUBSUB.md
- SPEC/REPO.md
- SPEC/STATS.md
- SPEC/SWARM.md
Tidy up the API docs by removing refs to Go as well as JavaScript (since this is the JS interface repo).
refs https://github.com/ipfs/interface-js-ipfs-core/issues/423
refs https://github.com/ipfs/interface-js-ipfs-core/pull/435
> docs: remove references to Go

- src/pin/ls.js
- src/pin/rm.js
Potential temporary fix for:
```
Error: EPERM: operation not permitted, rename 'C:\Users\travis\AppData\Local\Temp\ipfs-test-de2fc17f2aa28095e191f466fe8a6601\blocks\US\.3752.7204' -> 'C:\Users\travis\AppData\Local\Temp\ipfs-test-de2fc17f2aa28095e191f466fe8a6601\blocks\US\CIQPEUFLMK4TATXY3U6F7FNH33MIRA4KTFDAKY5ZKL7CCVQDQRIZUSQ.data'
```
This happens on the windows build in js-ipfs. Perhaps concurrent read/write is the issue?
> fix: populate in series

- SPEC/PUBSUB.md
- src/pubsub/unsubscribe.js
Hi, continuing issue #436  here as a PR preparing. (Not ready yet)
I created a PR both on [js-ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client/pull/940) and [js-libp2p](https://github.com/libp2p/js-libp2p/pull/321) as @alanshaw suggested.
If everything ok I will add tests to this repo as well. 
Let me know what you think.
> pubsub.unsubscribe without handler reference

- src/miscellaneous/resolve.js
Go-ipfs now normalizes paths before adding files. This will:
* remove any leading slashes.
* remove any `/./` components.
* normalize any `/../` components.
That breaks this test which assumes that paths are returned _exactly_ as specified.
> fix: don't expect ipfs to preserve a leading slash

- SPEC/SWARM.md
- src/swarm/addrs.js
If the common factory creates a node with no bootstrap nodes then getting a list of swarm addresses could be empty (or could also be empty anyway if the connection to the bootstrap nodes takes a long time). This PR spawns and connects another IPFS node to ensure that there should be swarm addresses available.
> fix: swarm addrs test

- src/object/links.js
This reverts commit ba4f788978d5a2767ff5c41272541ee6be8b2d2e.
> Remove test for Object.links with CBOR

- src/config/set.js
Anything that isn't a string needs to be passed with `--json` to the config set HTTP API. This PR tests that this is happening by virtue of setting a non string value.
> test: add test for config set with number

- SPEC/FILES.md
fix a couple of grammatical errors
arrange function index in alphabetical order
add more options to ipfs.add doc
rename cid-version to cidVersion in the docs
closes: #429
License: MIT
Signed-off-by: Prabhakar-Poudel <yuvrajzohan@gmail.com>
> docs(add): include all available options for ipfs.add function

- src/dht/provide.js
`cid-version` is how it should be used in a query string. In core we use `camelCase`.
> fix: use cidVersion option

- src/bitswap/utils.js
Also, every returns true if there's no items in the list so this was returning a false positive.
> fix: wait for one key to be the required key not all

- src/dht/find-provs.js
This adds a 3rd node to the mix for the dht findProvs test. We now add and provide the same content on two nodes, and then check providers from the 3rd node.
This test change ensures that we are able to get more than 1 provider.
required by https://github.com/ipfs/js-ipfs-http-client/pull/1041
> test: add find providers test for multiple providers

- SPEC/DAG.md
Add links from existing docs to ProtoSchool tutorials as part of our Q3 IPFS Docs effort. See issue: https://github.com/ProtoSchool/protoschool.github.io/issues/260
> Add links to ProtoSchool DAG API tutorials

- src/pin/ls.js
- src/pin/utils.js
This PR adds more detailed tests for `pin.ls`, including one that guards against issue described in https://github.com/ipfs/js-ipfs-api/pull/875
> fix: pin.ls ignored opts when hash was present

- src/name/resolve.js
Observed to fail in CI repeatedly.
Upped DNS retries also because same reason.
> chore: bigger timeout for name.resolve tests with key gens

- SPEC/FILES.md
- Change bullet formatting to make it possible to use the markdown headers to link specifically to the MFS portion of this document. 
- Link out from MFS section to the ProtoSchool tutorial as part of Q3 IPFS Docs initiative (see issue https://github.com/ProtoSchool/protoschool.github.io/issues/260)
> Edit formatting & link MFS to ProtoSchool

- src/files-mfs/ls-pull-stream.js
- src/files-mfs/ls-readable-stream.js
- src/files-mfs/ls.js
Will not pass in go-ipfs until `--long` is implemented.
https://github.com/ipfs/go-ipfs/pull/6528
> fix: use the correct option name for files.ls long

- SPEC/OBJECT.md
- src/object/stat.js
The opts parameter wasn't correctly passed in when calling ipfs.object.stat. This is the test that makes sure opts is being correctly passed to through the send function to the IPFS daemon. 
I've also removed the "base58" encoding that was being passed in for some tests as base58 isn't a valid option for encoding and would provide this error: 
Uncaught AssertionError: expected [Error: invalid encoding: base58] to not exist
> Added in a test for the opts parameter.

- src/files-regular/add.js
Output is:
```js
[
{
path: 'test-dir/b/jungle.txt',
hash: 'QmT6orWioMiSqXXPGsUi71CKRRUmJ8YkuueV2DPV34E9y9',
size: 2305
},
{
path: 'test-dir/b',
hash: 'QmfQm3xnDNKHRxPxb3z1UA81Cst8wWdA93dZC6oPRbTWHm',
size: 2362
},
{
path: 'test-dir/a/pp.txt',
hash: 'QmVwdDCY4SPGVFnNCiZnX5CtzwWDn6kAM98JXzKxE3kCmn',
size: 4551
},
{
path: 'test-dir/a/holmes.txt',
hash: 'QmR4nFjTu18TyANgC65ArNWp5Yaab1gPzQ4D8zp7Kx3vhr',
size: 582072
},
{
path: 'test-dir/a/alice.txt',
hash: 'QmZyUEQVuRK3XV7L9Dk26pg6RVSgaYkiSTEdnT2kZZdwoi',
size: 11696
},
{
path: 'test-dir/a',
hash: 'QmXh4P8PwnYDrN62u1GRunyhoEnW68vTR7TXkBxodkxsmw',
size: 598478
},
{
path: 'test-dir',
hash: 'QmVBueuZRsuNgvExGFyTUGcLs2pdUMaKWrXu5fY37BaT2T',
size: 600933
}
]
```
> test: add test for add files to dir non sequentially

- package.json
- src/pubsub/ls.js
- src/pubsub/peers.js
- src/pubsub/publish.js
- src/pubsub/subscribe.js
- src/pubsub/unsubscribe.js
- src/pubsub/utils.js
In the browser we can only make 5 concurrent requests to the same origin.
This PR also refactors the pubsub tests to use async/await and be less flakey.
> fix: reduce the number of concurrent requests in browser

- SPEC/PUBSUB.md
- src/pubsub/publish.js
On [libp2p/js-libp2p#365](https://github.com/libp2p/js-libp2p/pull/365), we decided to accept strings as the data being published. This usually was a barrier for entry users, so we just convert from string to buffer, if we receive a string.
Needs:
> chore: integrate libp2p new pubsub routing

- src/files-regular/add-from-url.js
- src/files-regular/utils.js
- src/utils/echo-http-server.js
> Required by https://github.com/ipfs/js-ipfs/pull/2304
Old version of `addFromURL` tests was Node-centric and did not work in web browser contexts.
This PR:
- moves the HTTP server to a separate file to enable spawning it from
aegir hook (see .aegir.js/hooks/browser/pre|post in js-ipfs from https://github.com/ipfs/js-ipfs/pull/2304)
- removes  overhead of starting and stopping HTTP servers multiple times
- shortens/simplifies test code a bit
> fix: tests of addFromURL in browsers

- package.json
- src/miscellaneous/id.js
- src/miscellaneous/resolve.js
- src/swarm/addrs.js
- src/swarm/connect.js
- src/swarm/disconnect.js
- src/swarm/local-addrs.js
- src/swarm/peers.js
This PR increases a couples of timeout and adds support for async/await setup in the swarm tests
More PRs will follow to move everything to async/await setup
the following PRs add support async setup:
https://github.com/ipfs/js-ipfs-http-client/pull/1105
https://github.com/ipfs/js-ipfs/pull/2428
> feat: add support for async/await setup in the swarm tests

- src/block/get.js
- src/block/stat.js
- src/bootstrap/add.js
- src/config/set.js
- src/files-mfs/ls.js
- src/object/data.js
- src/object/get.js
- src/object/links.js
- src/object/patch/add-link.js
- src/object/patch/append-data.js
- src/object/patch/rm-link.js
- src/object/patch/set-data.js
- src/object/stat.js
Our http tests in `js-IPFS` duplicate a whole bunch of tests from this suite, but they also test some unhappy paths that this suite does not.
I've pulled them out of `js-IPFS` as part of ipfs/js-ipfs#2495 and am adding them to the interface tests here.
> test: add missing tests

- package.json
- src/key/rename.js
- src/utils/mocha.js
Workaround for https://github.com/chaijs/chai/issues/1298
The order in which plugins are applied to chai is important and can break tests in other modules that run the tests from this one.
> fix: configure chai for use by other modules

- src/files-regular/add-from-url.js
I'm using one of those ISPs that 'helpfully' directs you to a search page if the URL you are accessing does not have a DNS match.
The URL used in the test was well formed but not a real domain though can be resolved, so this PR changes it to be something even a web-breaking DNS server would refuse to resolve.
> fix: make invalid url actually invalid

- src/bootstrap/add.js
Since it's not what we are testing here.
> chore: do not assert on removed bootstrap nodes

- SPEC/CONFIG.md
- src/config/profiles/apply.js
Also corrects `ipfs.config.profiles.list` example.
BREAKING CHANGE:
`ipfs.config.profiles.apply` now returns `original`/`updated` keys in the diff because using `new` stops us from destructuring in js.
Sort of breaking, no implementation for this has been published yet.
> docs: add dry-run config test and change new/old for original/updated

- README.md
- SPEC/BITSWAP.md
- SPEC/BLOCK.md
- SPEC/BOOTSTRAP.md
- SPEC/CONFIG.md
- SPEC/DAG.md
- SPEC/DHT.md
- SPEC/FILES.md
- SPEC/KEY.md
- SPEC/MISCELLANEOUS.md
- SPEC/NAME.md
- SPEC/OBJECT.md
- SPEC/PIN.md
- SPEC/PUBSUB.md
- SPEC/REFS.md
- SPEC/REPO.md
- SPEC/STATS.md
- SPEC/SWARM.md
This PR converts `interface-ipfs-core` docs examples to use async/await syntax.
Closes #525.
> chore: update examples in docs to async/await

- SPEC/OBJECT.md
This PR updates `object.links` API documentation with a real example.
In addition to #542, referring to this [comment](https://github.com/ipfs/interface-js-ipfs-core/pull/542).
> chore: update object links api with real example

- SPEC/FILES.md
Copying or moving from an IPFS path does _not_ recursively retrieve all contents from the network if not in your node's repo - it only retrieves the root node.
> docs: clarify MFS cp/mv from IPFS path

- src/dht/provide.js
This is in reference to https://github.com/ipfs/js-ipfs/pull/2589
Tests that dht.provide() works with a CID string
> Add dht.provide() test with string CID parameter

- src/utils/echo-http-server.js
`echo-server` was not handling properly error on both `start()` and `stop()` methods. 
@achingbrain suggested on https://github.com/ipfs/interface-js-ipfs-core/pull/565 's [review](https://github.com/ipfs/interface-js-ipfs-core/pull/565/files#r352515503):
```javascript
server.start = (opts) => new Promise((resolve, reject) => {
server.once('error', reject)
server.listen(Object.assign({ port: defaultPort, host: '127.0.0.1' }, opts), () => {
server.removeListener('error', reject)
resolve()
})
})
```
I think we just want to check `server.listen()` and `server.close()` related errors. For this reason, my suggestion is:
```javascript
server.start = (opts) => new Promise(
(resolve, reject) => server.listen(
Object.assign({ port: defaultPort, host: '127.0.0.1' }, opts), (err) => err ? …
```
> fix: handle err on both start and stop echo-server

- SPEC/FILES.md
UnixFS uses `dag-pb` so don't offer the user the option of using other formats.
> docs: remove format option from mfs commands

- src/swarm/disconnect.js
Disconnecting by a multiaddr isn't reliable as we're not always guaranteed to have a PeerId in the multiaddr. Using a PeerId is reliable. This updates the disconnect test to use the PeerId of the peer instead of the multiaddr
> fix: disconnect by peerid not multiaddr

- SPEC/FILES.md
- src/files-mfs/flush.js
`ipfs.files.flush` returns the CID of the flushed path since [`go-IPFS@v0.4.20`](https://github.com/ipfs/go-ipfs/pull/6223/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR141).
It also only takes one path as an optional parameter.
> docs: update files.flush return type

- src/files-mfs/stat.js
- src/files-regular/add-pull-stream.js
- src/files-regular/add.js
Also asserts that `.add` output has metadata
> test: add tests for mfs stat with metadata

- SPEC/BITSWAP.md
- SPEC/DHT.md
- SPEC/MISCELLANEOUS.md
- SPEC/SWARM.md
- package.json
- src/dht/find-peer.js
- src/miscellaneous/id.js
- src/pubsub/peers.js
- src/pubsub/subscribe.js
- src/swarm/addrs.js
- src/swarm/peers.js
- src/utils/mocha.js
As part of the async iterator refactor some peer IDs were being returned as CIDs - the conversion was done in IPFS but not in libp2p, which meant that where IPFS exposes libp2p directly, peer IDs were being returned as strings, e.g. pubsub topic subscribers, message senders, etc.
The aim is to convert these to CIDs in the long run but such a change needs to be driven from inside libp2p instead of piecemeal at the IPFS layer.
This PR changes the `ipfs.id().id` and `ipfs.swarm.peers().[].peer` properties to strings so we can do the CID conversion in one go.
Also adds more in-depth tests for `ipfs.id` and documents the output from that method.
BREAKING CHANGE:
Where `PeerID`s were previously [CID]s, now they are Strings
- `ipfs.bitswap.stat().peers[n]` is now a String (was a CID)
- …
> refactor: return peer ids as strings

- src/bitswap/wantlist.js
- src/miscellaneous/resolve.js
- src/ping/ping.js
- src/pubsub/peers.js
- src/pubsub/subscribe.js
- src/swarm/addrs.js
- src/swarm/connect.js
- src/swarm/disconnect.js
- src/swarm/peers.js
Passing `type: 'js'` requires the containing project to have a dependency on js-IPFS which may not be the case.
I don't think anything in these tests requires the js implementation.  Please do shout if something does.
> fix: do not assume certain implementations of ipfs are present

- src/object/stat.js
fixes "expected 1.999 to be at least 2" in CI
> fix: add object.stat timeout leeway

- SPEC/FILES.md
The links to regular files api examples were broken.
Also makes the 'importing from a url' and 'importing from the file system' headers linkable.
> docs: fix examples links
