README.md
package.json
src/object.js

**WIP**.. this is going to be big

object api tests

---

src/object.js

Also added some more blocks to see better grouping of commands

fix: before and after clauses need to be nested in a describe block

---

package.json
src/object.js

feat(object): object.put protobuf encoding test

---

README.md

Reverts ipfs/interface-ipfs-core#15

Revert "draft api docs for blocks"

---

README.md

s/interface-stream-muxer/interface-ipfs-core, and a couple of other small tweaks.

Fix README typo + tweaks.

---

API/config/README.md
src/config.js
src/index.js

config API

---

src/config.js
src/files.js
src/object.js

This fixes the test failures in ipfs/js-ipfs#392
@diasdavid please review

fix: ensure promise tests are correct

---

API/block/README.md
package.json
src/block.js

Make block API spec and tests coherent.

---

API/swarm/README.md
src/swarm.js

Refs 
- https://github.com/ipfs/js-ipfs/pull/489
- https://github.com/ipfs/js-ipfs-api/pull/380

feat(swarm): expose PeerInfo for addrs command

---

src/files.js

Ref https://github.com/ipfs/js-ipfs-api/pull/384

fix(get): update tests to reflect the tar-stream behaviour

---

API/swarm/README.md
package.json
src/swarm.js

Ref https://github.com/ipfs/js-ipfs-api/pull/427

feat: prepare for swarm.peers changes in 0.4.5

---

src/config.js

all we need for `js-ipfs 0.21`:)

fix(config): make promise tests actually test the full promise chain

---

README.md

for https://github.com/ipfs/docs/issues/23

docs: list all calls in the readme

---

package.json
src/block.js
src/config.js
src/dag.js
src/dht.js
src/files.js
src/generic.js
src/object.js
src/pin.js
src/pubsub.js
src/swarm.js

Ref https://github.com/ipfs/js-ipfs/issues/787

[WIP] upgrade to new block interface

---

src/object.js

These tests will pass after https://github.com/ipfs/js-ipfs/pull/849 is merged

testing(): add object.get tests for multihash string

---

src/pubsub.js

This currently fails in js-ipfs-api.
issue: https://github.com/ipfs/js-ipfs-api/issues/569
fix PR: https://github.com/ipfs/js-ipfs-api/pull/570

test: add test for ipfs.pubsub.publish with a binary (non-utf8) buffer

---

src/swarm.js

Swarm Tests - WIP

---

src/pin.js

Get tests passing with pin core changes (#63)

---

package.json

 aegir is a dependency

---

src/swarm.js

See https://github.com/ipfs/js-ipfs/issues/1075

test: use os.tmpdir()

---

src/pubsub.js

Here's a test for #174 that currently fails.

test(pubsub): subscribe with a Promise

---

src/key.js

The key remove test was wrong.  This should fix https://github.com/ipfs/js-ipfs-api/pull/641

fix: key.rm test

---

SPEC/KEY.md
src/key.js

Ref.: https://github.com/ipfs/js-ipfs-api/pull/659

Normalize KEY API

---

SPEC/PUBSUB.md
src/pubsub.js

...and removes the timeout...it shouldn't be required
Also fixes a typo I noticed in the pubsub spec.

Fixes timeout ms arg being erroneously passed to pubsub.peers 

---

src/block.js
src/config.js
src/dag.js
src/dht.js
src/files.js
src/key.js
src/miscellaneous.js
src/object.js
src/pin.js
src/pubsub.js
src/swarm.js

This reverts commit 4d4ef7f043db4f8a3f0f847b1af05453341b6228.

Revert "feat: use new ipfsd-ctl (#186)"

---

src/stats.js

Ref.: https://github.com/ipfs/js-ipfs/pull/1189

fix: stats not implemented on jsipfs

---

js/src/pubsub.js

Always unsubscribe the feeds. This way subsequent tests won't
fail randomly.

test: Improve pubsub test isolation

---

js/src/files-mfs.js
js/src/files.js
js/src/key.js
js/src/stats.js

use mocha's skip for conditional tests

---

js/src/miscellaneous.js

When stopping an IPFS node it returns an error. The error message
depends on the environment. In Browsers it might also return
`Failed to fetch` or `XHR error`. Hence removing the specific
error check as it would fail for Browsers.

fix: don't error to specific

---

js/src/files.js

Tests for `files.add` with pull streams issues identified here https://github.com/ipfs/js-ipfs-api/issues/745 and here https://github.com/ipfs/js-ipfs/issues/1317

feat: adds pull stream tests for files.add

---

js/src/dag.js
js/src/dht.js
js/src/key.js
js/src/miscellaneous.js
js/src/pubsub.js
js/src/swarm.js
js/src/utils/spawn.js

Simple utility to reduce some repetition and ease node creation.

feat: add utils to spawn multiple nodes and get their ID

---

js/src/utils/spawn.js

Pending resolution of https://github.com/ipfs/js-ipfsd-ctl/issues/253

fix: spawn in series

---

js/src/ping.js

Investigation discovered that pong responses CAN have `time: 0` (they can be very quick). Previously pong messages were differentiated by time greater than 0, but considering it can be 0 this was incorrect.

fix: correctly differentiate pong responses

---

js/src/object.js

Fixes flaky test & removes unused vars

fix: wait for put in object.patch.addLink before hook

---

SPEC/FILES.md

Took the description from go-ipfs.
Fixes  #294

Add docs for the pin option for files.add*

---

js/src/dag.js

See ipfs/interface-ipfs-core#314 for context

test: backport of ipfs/interface-ipfs-core#314

---

js/src/files/index.js
js/src/files/read-pull-stream.js
js/src/files/read-readable-stream.js

Just realised these have been missed.

test: adds tests for mfs files.read*Stream

---

SPEC/MISCELLANEOUS.md
js/src/miscellaneous/index.js
js/src/miscellaneous/resolve.js

"should resolve IPNS link recursively" takes > 1min on my laptop. I'm open to suggestions on how to speed this up...
refs https://github.com/ipfs/js-ipfs-api/pull/794 and https://github.com/ipfs/js-ipfs/pull/1455

test: add tests and docs for ipfs.resolve

---

js/src/config/get.js
package.json

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

fix: expect config to be an object

---

js/src/miscellaneous/resolve.js

The resolve IPNS link recursively test uses name.publish to publish an IPNS link as the value for the peer. It then uses resolve to resolve the peer ID and recursively then resolve the IPNS link.
This fixes the test so that when name.publish is called there is another connected node to publish to so that we do not get the error "failed to find any peer in table", in the case that the node has not yet connected to any other peers.

fix: ensure test for resolve recursive has another node

---

SPEC/DAG.md

Closes #307
License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>

fix(spec/dag): fix wrong example output for sha3-512 hash algorithm

---

SPEC/FILES.md

Requires ipfs/js-ipfs#1469 to be released

docs: add chunker option to files.add documentation

---

SPEC/BITSWAP.md
SPEC/STATS.md

Fixes description, return types and example.

fix: bitswap.stat docs

---

js/src/dag/get.js
js/src/dag/tree.js
package.json

This 0.13.0 ipld-dag-dbor release contains breaking changes
hence special care is needed.

chore: upgrade ipld-dag-cbor to 0.13.0

---

CODEOWNERS

I don't believe that this file is stating the current reality nor do I know that we effectively use this as part of our contributing guidelines.

chore: delete codeowners

---

js/src/files-regular/add.js
js/src/utils/mocha.js
js/test/fixtures/hidden-files-folder/ipfs-add.js

test: additional add* validation tests

---

SPEC/BITSWAP.md
SPEC/BLOCK.md
SPEC/BOOTSTRAP.md
SPEC/CONFIG.md
SPEC/DAG.md
SPEC/DHT.md
SPEC/FILES.md
SPEC/KEY.md
SPEC/MISCELLANEOUS.md
SPEC/NAME.md
SPEC/OBJECT.md
SPEC/PIN.md
SPEC/PUBSUB.md
SPEC/REPO.md
SPEC/STATS.md
SPEC/SWARM.md

This has been bugging me forever. Swap the code blocks so they're around the code.

fix: code blocks for the code

---

js/src/ping/ping-pull-stream.js
js/src/ping/ping-readable-stream.js
js/src/ping/ping.js

This takes around 15s locally and can take significantly longer in CI.

chore: increase ping timeouts

---

js/src/dht/findpeer.js
js/src/dht/findprovs.js
js/src/dht/get.js
js/src/dht/provide.js
js/src/dht/query.js

Taking into account the failures in CI for `js-ipfs`: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/master/78/pipeline/257

test: increase tests timeouts

---

SPEC/FILES.md

Fix for link in README
https://github.com/ipfs/interface-ipfs-core/issues/410

fix: updated link in readme

---

CHANGELOG.md
SPEC/FILES.md
js/src/files-regular/add-from-url.js
js/src/files-regular/index.js

Inconsistently `addFromUrl` in some places...

fix: addFromURL case

---

js/src/files-regular/ls.js

for https://github.com/ipfs/js-ipfs-http-client/pull/914

test: add test for ls by IPFS path

---

SPEC/FILES.md

Just realized that I forgot to create a PR a while back. Still relevant IMHO - default hashing mechanism should be in the comments as well as the link to the list of possible hashing types

Adding some addtl comments on where to find various hashing codes and defaults

---

SPEC/MISCELLANEOUS.md
src/miscellaneous/dns.js

See: #377 and https://github.com/ipfs/js-ipfs/issues/1935

test:  tests and updated documentation for recursive dns

---

maintainer.json

In preparation for https://github.com/ipfs/team-mgmt/pull/822

docs: add maintainer.json

---

.travis.yml

See https://github.com/ipfs/aegir/issues/345

chore: remove commitlint from check stage in CI

---

SPEC/SWARM.md

docs(swarm local address): add documentation spec for swarm.localAddrs

---

.aegir.js
package.json
src/block/put.js
src/block/stat.js
src/dag/put.js
src/files-regular/refs-tests.js
src/pubsub/subscribe.js

chore(package): update aegir to version 19.0.3

---

src/dht/get.js
src/dht/index.js
src/dht/put.js

This is the work from #383 but updated again!
closes https://github.com/ipfs/interface-js-ipfs-core/pull/383

fix: dht tests

---

src/object/links.js
src/repo/gc.js

Depends on PR for refs: https://github.com/ipfs/interface-js-ipfs-core/pull/460

Tests for Garbage Collection

---

SPEC/REPO.md

See https://github.com/ipfs/js-ipfs-http-client/pull/992

Fix docs for repo.gc() response format

---

src/dag/get.js

Made by @achingbrain for https://github.com/ipfs/js-ipfs-http-client/pull/957

test: add additional DAG CBOR and raw tests

---

src/miscellaneous/resolve.js

name.publish needs at least one other node to publish to.

fix: resolve IPNS recursively test

---

package.json
src/dht/provide.js
src/files-regular/add-from-fs.js
src/files-regular/add-from-stream.js
src/files-regular/add.js

This PR updates the tests with new supported inputs for add.
refs https://github.com/ipfs/js-ipfs-http-client/pull/1087

fix: supported add inputs

---

SPEC/CONFIG.md
src/config/index.js
src/config/profiles/apply.js
src/config/profiles/index.js
src/config/profiles/list.js

This is only in js-IPFS for the time being

feat: add test and docs for listing config profiles

---

SPEC/BLOCK.md
src/block/index.js
src/block/rm.js

docs(block.rm) add block remove documentation
License: MIT
Signed-off-by: Prabhakar-Poudel <yuvrajzohan@gmail.com>

test(block.rm): add block remove tests

---

src/name/resolve.js

This PR adds IPFS test for resolving paths with libp2p-key represented as CIDv1 Base32.
Context:
- https://github.com/libp2p/specs/blob/master/RFC/0001-text-peerid-cid.md
- https://github.com/ipfs/js-ipfs/pull/2566
cc https://github.com/libp2p/specs/issues/216, https://github.com/ipfs/ipfs/issues/337

feat: test ipns resolve of peerid as cid

---

SPEC/DAG.md

Was added in https://github.com/ipfs/js-ipfs/pull/2521 but not updated here.

docs: add pin option to dag.put

---

SPEC/NAME.md
src/miscellaneous/resolve.js
src/name/publish.js
src/name/resolve.js

Should be camel case in core `allowOffline: true` and kebab case in querystring `?allow-offline=true` and CLI `--allow-offline`.

fix: allow offline option casing

---

SPEC/PIN.md
src/pin/ls.js

Adds a test to ensure pin.ls with multiple CIDs works correctly!

test: pin.ls with multiple CIDs

---

src/utils/echo-http-server.js

This PR refactors echo server `start()` and `stop()` from `callback` to `promise`.

refactor: http-server util file

---

src/bitswap/wantlist.js
src/files-regular/ls.js
src/key/list.js
src/key/rename.js
src/key/rm.js
src/miscellaneous/resolve.js
src/name-pubsub/cancel.js
src/name-pubsub/subs.js
src/name/resolve.js
src/object/data.js
src/object/links.js
src/object/patch/append-data.js
src/object/patch/set-data.js
src/object/stat.js
src/pubsub/subscribe.js

chore: remove lint nested callbacks overrides

---

src/add.js

test: adds test for adding directories with --only-hash

---

package.json
src/block/put.js

refs https://github.com/ipfs/js-ipfs/issues/2751

test: block put with CID string

---

package.json

closes https://github.com/ipfs/interface-js-ipfs-core/issues/591

chore(package): update ipfs-utils to version 0.7.2
